### ISSUE TITLE
Navigation does not work

### ISSUE THREAD

**Issue by georgejecook** [rokudev/atomio-package#2]
I tried with ctags; but as far as I can tell, there is no navigation capability at all. Unless I'm missing something. How do you guys navigate to methods? I can declare a method in the _same_ file, and it has _no idea_ that the method is there.

Navigation is fundamental for me - I can't move from eclipse (where I wrote a plugin to improve the shoddy navigation) until this is addressed, which is a shame coz it looks great.

**Comment by yurii-polishchuk** [comment]
Thank you for your request, but the atomio package was decommissioned and is no longer maintained.
